### ISSUE TITLE
`xattr: ./Tesseract.app: No such xattr: com.apple.quarantine`

### ISSUE THREAD

**Issue by namtonthat** [mr-pennyworth/alfred-clipboard-ocr#2]
Installation fails on macOS Ventura as reported on these posts as well: 

![image](https://user-images.githubusercontent.com/91519364/209434845-d93e6bf8-d32b-47ca-9beb-60c1f3684b0d.png)

Have attempted to install `Tesseract` via `brew` using `brew install tesseract` and adjusting the location to install the script i.e. 

Updating `Create and load LaunchAgent for ocr.py` to this: 
```
mkdir ~/Library/LaunchAgents
cat <<EOF > ~/Library/LaunchAgents/alfred-clipboard-history-ocr.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Label</key>
	<string>alfred-clipboard-history-ocr</string>
	<key>ProgramArguments</key>
	<array>
		<string>/usr/bin/python3</string>
		<string>$(pwd)/ocr.py</string>
	</array>
	<key>RunAtLoad</key>
	<true/>
	<key>StandardErrorPath</key>
	<string>/tmp/alfred-clipboard-history-ocr.out</string>
	<key>StandardOutPath</key>
	<string>/tmp/alfred-clipboard-history-ocr.out</string>
	<key>WatchPaths</key>
	<array>
		<string>$HOME/Library/Application Support/Alfred/Databases/clipboard.alfdb.data</string>
	</array>
</dict>
</plist>
EOF

sudo xattr -d com.apple.quarantine /opt/homebrew/bin/Tesseract
launchctl unload ~/Library/LaunchAgents/alfred-clipboard-history-ocr.plist
launchctl load -wF ~/Library/LaunchAgents/alfred-clipboard-history-ocr.plist
```

Throws this error: 
```
[22:44:28.837] Logging Started...
[22:44:31.742] Clipboard History OCR[Keyword] Processing complete
[22:44:31.743] Clipboard History OCR[Keyword] Passing output '' to Run Script
[22:44:31.766] STDERR: Clipboard History OCR[Run Script] mkdir: /Users/namtonthat/Library/LaunchAgents: File exists
xattr: ./Tesseract.app: No such xattr: com.apple.quarantine
```

*System settings:*
- Apple M1 Pro 
- MacOS Ventura 13.0.1

**Comment by mr-pennyworth** [comment]
@namtonthat it is very likely that the bundled `Tesseract.app` doesn't work on M1 macs. Since you have already installed `tesseract` via `brew`, you can edit the python file `ocr.py` in the workflow directory and set `TESSERACT` and `TESSDATA` variables appropriately to point to the directories corresponding to your own installation.

<img width="627" alt="image" src="https://github.com/mr-pennyworth/alfred-clipboard-ocr/assets/74945464/030e256e-fd2f-4cd7-9d85-ecd0c564f344">
