### ISSUE TITLE
A way to bring back default image size in Alfred's clipboard?

### ISSUE THREAD

**Issue by yarub123** [mr-pennyworth/alfred-clipboard-ocr#4]
The person who made this workflow is a FKN BEASTTTTT. It works so deliciously. Great work dude. I am at a loss for words at how elegant this is. Respect!!

@mr-pennyworth Hope you're well Penny. As always you have some delicious workflows and work that you've done... Thank you for being so helpful to others whilst still delivering deliciousness.

Small question (Sorry I know this is like a year later on a closed issue):

-     Is it possible to bring back the info that used to come up under the image....

-     Like the image size that used to come up by default when browsing through the clipboard?

-     After installing the OCR, it no longer shows the image size

**Comment by mr-pennyworth** [comment]
<img width="560" alt="image" src="https://github.com/mr-pennyworth/alfred-clipboard-ocr/assets/74945464/ce0f9fe7-753f-48a3-a9ac-17f0ba90d378">

I won't be able to make the above change and upload to github any time soon, but you can go ahead and edit the `ocr.py` file in your workflow directory as shown above.

Thanks! Glad to know you find the workflow useful! :)
