### ISSUE TITLE
Screenshots do not appear in clipboard history

### ISSUE THREAD

**Issue by kalaschnik** [mr-pennyworth/alfred-clipboard-ocr#6]
I am on macOS `14.2.1 (23C71)` running Alfred `5.5 [2257]`. If I run a screen capture with ⌘⌃⇧4, the image is not showing in my clipboard histroy.  Although it is in the clipboard, since I can paste it via Preview -> File new from Clipboard

**Comment by mr-pennyworth** [comment]
Thanks for the report, @kalaschnik!

If images are not appearing at all, it is likely a clipboard history issue, and not an issue with `alfred-clipboard-ocr`. If the OCR stops working or has a bug, the images will still show up in the clipboard history, just that they won't be annotated with the text from the images.

Make sure you go to "Features" (1) > "Clipboard History" (2) and then confirm that you have images enabled by checking the "Keep Images" (3) checkbox.
<img width="1005" alt="image" src="https://github.com/mr-pennyworth/alfred-clipboard-ocr/assets/74945464/624ae4d9-f224-4d03-8ef2-69be0945154a">

If this still doesn't work, best would be to reach out to folks https://www.alfredforum.com. The community is very helpful there, and they'll be able to help you out 😇

**Comment by kalaschnik** [comment]
The tick was checked, but now I waited a bit. I think running `.clipboard-history-ocr-install` need some seconds before it starts working? All good now :)
