### ISSUE TITLE
The workflow doesnt work

### ISSUE THREAD

**Issue by arturasvlt** [mr-pennyworth/alfred-clipboard-ocr#7]
Hi,

So I type clipboard
<img width="769" alt="image" src="https://github.com/mr-pennyworth/alfred-clipboard-ocr/assets/142324025/4b3d35c0-0589-414a-8bad-e80b1e3e053d">
and try to enter a search keyword. While I see all the images in the clipboard, they are still not searchable. Im not sure what's wrong.. I am on macOS Sonoma

**Comment by mr-pennyworth** [comment]
Thanks @arturasvlt for reporting!
The screenshot you posted isn't about this workflow.
This is meant to make your clipboard images searchable via OCR. `clip` is a workflow of its own and isn't related.
