### ISSUE TITLE
[BUG] OCR only runs manually. Not automatically. 

### ISSUE THREAD

**Issue by yarub123** [mr-pennyworth/alfred-clipboard-ocr#8]
Appears to be likely a similar (permissions) issue that is causing my Alfred Extra Pane persistent permissions request as well.

**Describe the bug**
It installs the plist in launch agents correctly, however it does not OCR images... Running ocr.py through terminal however DOES work and it starts the process of running OCR on any images in the clipboard. On older mac it used to do the OCR process automatically as soon as image was saved to clipboard

I have tried version 0.1.2 (most up to date as of now). Then I tried 0.0.3. Same issue. Only works via terminal. Tried running chmod on all the necessary files + a few other things. 

**Logs**
`cat /tmp/alfred-clipboard-history-ocr.out
/Applications/Xcode.app/Contents/Developer/usr/bin/python3: can't open file '/Users/yakub/Documents/Alfred.alfredpreferences/workflows/user.workflow.4D6ED4B6-DAB3-42A7-9685-D66905DB5264/ocr.py': [Errno 1] Operation not permitted
/Applications/Xcode.app/Contents/Developer/usr/bin/python3: can't open file '/Users/yakub/Documents/Alfred.alfredpreferences/workflows/user.workflow.4D6ED4B6-DAB3-42A7-9685-D66905DB5264/ocr.py': [Errno 1] Operation not permitted
/Applications/Xcode.app/Contents/Developer/usr/bin/python3: can't open file '/Users/yakub/Documents/Alfred.alfredpreferences/workflows/user.workflow.4D6ED4B6-DAB3-42A7-9685-D66905DB5264/ocr.py': [Errno 1] Operation not permitted
/Applications/Xcode.app/Contents/Developer/usr/bin/python3: can't open file '/Users/yakub/Documents/Alfred.alfredpreferences/workflows/user.workflow.4D6ED4B6-DAB3-42A7-9685-D66905DB5264/ocr.py': [Errno 1] Operation not permitted
/Applications/Xcode.app/Contents/Developer/usr/bin/python3: can't open file '/Users/yakub/Documents/Alfred.alfredpreferences/workflows/user.workflow.4D6ED4B6-DAB3-42A7-9685-D66905DB5264/ocr.py': [Errno 1] Operation not permitted
/Applications/Xcode.app/Contents/Developer/usr/bin/python3: can't open file '/Users/yakub/Documents/Alfred.alfredpreferences/workflows/user.workflow.4D6ED4B6-DAB3-42A7-9685-D66905DB5264/ocr.py': [Errno 1] Operation not permitted
/Applications/Xcode.app/Contents/Developer/usr/bin/python3: can't open file '/Users/yakub/Documents/Alfred.alfredpreferences/workflows/user.workflow.4D6ED4B6-DAB3-42A7-9685-D66905DB5264/ocr.py': [Errno 1] Operation not permitted
/Applications/Xcode.app/Contents/Developer/usr/bin/python3: can't open file '/Users/yakub/Documents/Alfred.alfredpreferences/workflows/user.workflow.4D6ED4B6-DAB3-42A7-9685-D66905DB5264/ocr.py': [Errno 1] Operation not permitted
/Applications/Xcode.app/Contents/Developer/usr/bin/python3: can't open file '/Users/yakub/Documents/Alfred.alfredpreferences/workflows/user.workflow.4D6ED4B6-DAB3-42A7-9685-D66905DB5264/ocr.py': [Errno 1] Operation not permitted
/Applications/Xcode.app/Contents/Developer/usr/bin/python3: can't open file '/Users/yakub/Documents/Alfred.alfredpreferences/workflows/user.workflow.4D6ED4B6-DAB3-42A7-9685-D66905DB5264/ocr.py': [Errno 1] Operation not permitted
/Applications/Xcode.app/Contents/Developer/usr/bin/python3: can't open file '/Users/yakub/Documents/Alfred.alfredpreferences/workflows/user.workflow.4D6ED4B6-DAB3-42A7-9685-D66905DB5264/ocr.py': [Errno 1] Operation not permitted`

**System**
 - macOS version 14.7
 - Alfred version 5.5

**Comment by yarub123** [comment]
Only way around this was to disable SIP

**Comment by yarub123** [comment]
Fixed this and the AEP persistent permissions by disabling SIP 😞. Oh well. Screw SIP 🙃

**Comment by mr-pennyworth** [comment]
@yarub123 surprising that sip needs to be disabled for this...
What if you give full disk access to the python executable?
also, curious about usage of `/Applications/Xcode.app/Contents/Developer/usr/bin/python3` instead of `/usr/bin/python3`. Would that make a difference?

**Comment by yarub123** [comment]
@mr-pennyworth I was surprised as well. I think it's because of Apple's more stringent policies on Sonoma... (are you even on Sonoma yet? lol). Also the Xcode python was a curveball for me as well, as I checked your code and I didn't see anywhere calling for it, but even after editing ocr.py, the cat output still showed it was using Xcode's python 🙃)

And yeah dude trust me I tried giving full access to the python executable, as well as giving app management and developer permissions to it, Xcode, Alfred, AEP, etc. (And I tried both directories, as well as the python3 in the homebrew directory (/opt/homebrew/bin/python3)...(in fact that's the shebang I'm using in the now edited ocr.py file... and made a few extra changes to ocr.py)

But yeah. Now it all works. I believe it's some kind of extra code signing nonsense Apple imposed... It was for that reason i tried to get a developer id from Apple, but they rejected me, I have to call developer support. 

As always, wanted to say I love you for all the lovely workflows you have made. They are the bread and butter of my life, you should be a teacher or something idk man ur a smart dude ❤️

**Comment by mr-pennyworth** [comment]
oh damn! Guess I should delay Sonoma upgrade! 🙈
